name: network_request
description: A powerful and comprehensive Dart package for simplifying HTTP requests and interacting with RESTful APIs
version: 0.0.3+1
repository: https://github.com/ZakaTiwana/network_request

environment:
  sdk: '>=2.17.1 <4.0.0'

dependencies:
  http: ^1.4.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2
