name: network_request
description: A package to send network request in an organized manner. http package is used to make actual request
version: 0.0.2
repository: https://github.com/ZakaTiwana/network_request

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  http: ^0.13.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
